banning installing by full path, as well as using --inject-checksums and --robot as ebuser

diff --git a/eb b/eb
--- a/eb
+++ b/eb
@@ -72,7 +72,8 @@ if [ -z $USE_GENTOO ]; then
     export EASYBUILD_OPTARCH="$EASYBUILD_OPTARCH;GCCcore:GENERIC"
 fi
 
-if [ "$(whoami)" != "ebuser" ] ; then
+CURRENT_USER="$(whoami)"
+if [ "$CURRENT_USER" != "ebuser" ] ; then
 	export EASYBUILD_PREFIX=$HOME/.local/easybuild
 	export EASYBUILD_SUBDIR_USER_MODULES=''
         export EASYBUILD_REPOSITORY='FileRepository'
@@ -100,4 +101,25 @@ if [ ! -d /cvmfs/local ]; then
 fi
 export PYTHONPATH=$EASYBUILD_ROOT:$EASYBUILD_ROOT/site-packages
 export RSNT_EASYBUILD_MAGIC_COOKIE=263ca73bb634185aab1d1b41627fdbba
+
+# argument validation
+for argument in "$@"; do
+	echo $argument
+	if [[ $CC_CLUSTER == "build-node" ]]; then
+		if [[ $argument =~ .*.eb$ ]]; then
+			if [[ $argument =~ .*/.* ]]; then
+				echo "Please do not use a path to specify the easyconfig."
+				echo "Error on argument: $argument"
+				exit 1
+			fi
+		fi
+	fi
+	if [[ "$CURRENT_USER" == "ebuser" ]]; then
+		if [[ $argument =~ --inject-checksums* || $argument =~ --robot* || "$argument" == "-r" ]]; then
+			echo "Please do not use $argument as $CURRENT_USER"
+			exit 1
+		fi
+	fi
+done
+
 exec $EASYBUILD_ROOT/framework/eb --configfiles=$LOCAL_EASYBUILD_CONFIGFILES ${1+"$@"}
